name: reactAction
on:
  push:
    branches:
      - master
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: install
        env:
          ACCESS_TOKEN: ${{ secrets.reactAction }}
          BRANCH: gh-pages
          BUILD_SCRIPT: npm install
      - name: build
        env:
          ACCESS_TOKEN: ${{ secrets.reactAction }}
          BRANCH: gh-pages
          FOLDER: dist
          BUILD_SCRIPT: npm run build
