name: reactAction
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout

    - name: Build and Deploy
      env:
        ACCESS_TOKEN: ${{ secrets.reactAction }}
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: npm install && npm run build
